# -*- coding: utf-8 -*-
"""Estrutura_de_dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-XqxbTNG6lOYbTQKa2CvxxCoxVhiy6-e

# **Listas**
"""

# Criando uma lista em Python. Usamos os [] colchetes

animais = [1,2,3]
animais

animais = ["cachorro", "gato", 12345, 6.5]
animais

# Imprimindo o primeiro elemento da lista
animais[0]



# substituindo o primeiro elemento da lista
animais[0] = "papagaio"

animais

# Removendo um elemento da lista
animais.remove("gato")
animais

"gato" in animais

# descobrindo o tamanho da lista
len(animais)

lista = [500, 30, 300, 80, 10]

max(lista)

lista = [500, 30, 300, 80, 10]

min(lista)

# Adicionando um elemento

animais.append("Leão")
animais

# O append suporta apenas um elemento por comando
# caso se tente usar dois teremos um erro

animais.append("cobra", "cachorro")

# Para adicionar mais de um elemento usa-se o método .extend entre []

animais.extend(["cobra", "cachorro"])
animais

# Se usarmos [] para adicionar mais elementos com o append será criado uma lista aninhada
animais.append(["tartaruga", "gavião"])
animais

# Ordenando uma lista com .sort()
lista = [500, 80, 10, 30, 200]
lista

lista.sort()
lista

lista.extend([500, 100, 100, 50])
lista

lista.count(100)

"""**TUPLAS**"""

# As tuplas usam parentesis com sintaxe como as listas. No entanto as tuplas são imutáveis. Usamos os parentesis ()
tupla = ("banana", "maça", 10,50)
tupla

# veja o que ocorre se tentarmos alterar o elemento tupla[0] de banana para laranja:
tupla[0] = "laranja"

"""**DICIONARIO**"""

# Dicionario é uma estrutura do tipo chave-valor. Usamos as {} chaves

dicionario = {"Banana":15, "Maça":20, "Uva": 30, "Laranja": 10}
dicionario

# Acessando o valor de um elemento do dicionario. Nesse caso usamos os []
dicionario ["Uva"]

# Aalterando o valor de um elemento do dicionario. 
dicionario["Laranja"] = 50
dicionario

# Retornando todas as chaves do dicionario

dicionario.keys()

# Retornando todos os valores do dicionario

dicionario.values()

# Verificando se exite uma chave no dicionario e caso não exista inseri-la
dicionario.setdefault("Limão", 30)
dicionario

# Inserindo chave já existente (Laranja) e tentando mudar o valor para 40
dicionario.setdefault("Laranja", 40)